
#---standard pioneer footprint---
#---(in meters)---
robot_radius: 0.135


transform_tolerance: 1.0
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 2.5
 raytrace_range: 3.0
 inflation_radius: 0.2
 track_unknown_space: true
 combination_method: 1


 publish_voxel_map: true
 footprint_clearing_enabled: true

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}


inflation_layer:
 cost_scaling_factor:  50.0 #12.0  # exponential rate at which the obstacle cost drops off (default: 10)
 inflation_radius:     0.1 #0.27  #0.3 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
