global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0   # 0.5
  publish_frequency: 1.0    # 0.5
  # static_map: true
  rolling_window: false
  resolution: 0.05
  transform_tolerance: 1.2  #  3.0
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}


GlobalPlanner:        
   allow_unknown:  true