port: /dev/base_serial_port #ttyUSB0 # base_serial_port
baud: 921600 # 115200 
base_frame: base_link
odom_frame: odom
joy_topic:  /joy
odom_topic: /odom
base_shape_a: 0.2169
wheel_radius: 0.04657 
vel_topic: /cmd_vel
# provide_odom_tf: true
cmd_timeout: 0.2
serial_timeout: 50
linear_speed_max:  3.0
angular_speed_max: 3.14
Mileage_file_name:  car_Mileage_info.txt
debug_log:  false




linear_correction_factor: 1.00  #线速度校准系数
angular_correction_factor: 1.00  #角速度校准系数

#publish_odom_transform: True   #是否发布odom->base_footprint坐标变换
Kp: 350                         #OpenCRP电机控制PID，P参数
Ki: 0                           #OpenCRP电机控制PID, I参数
Kd: 200                         #OpenCRP电机控制PID，D参数

control_rate: 50                #底盘控制频率  