global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 2.0
   publish_frequency: 1.0
   #static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 1.2
   #map_type: costmap
   plugins:
           - {name: static_layer,       type: "costmap_2d::StaticLayer"}
           - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}
   cost_scaling_factor: 50 #80 #60.0  # exponential rate at which the obstacle cost drops off (default: 10)
   inflation_radius:     0.15 #0.2 # max. distance from an obstacle at which costs are incurred for planning paths.

GlobalPlanner:        
   allow_unknown:  true
